name: topcow-claim
version: "1.0.0"
display_name: "TopCoW CLAIM"

type: segmentation
framework: nnunet
domain: neuroimaging

description: >
  TBA

weights:
  location: /run/user/11503/gvfs/smb-share:server=tierra.cnic.es,share=sc/LAB_FSC/LAB/PERSONAL/imarcoss/ai_models/imaging/Neuroimaging/TopCoW/CLAIM/v1.0.0
  structure: hybrid_nnunet_yolo
  files:
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/fold_0/checkpoint_best.pth
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/fold_1/checkpoint_best.pth
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/fold_2/checkpoint_best.pth
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/fold_3/checkpoint_best.pth
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/fold_4/checkpoint_best.pth
    - yolo_best.pt
  config_files:
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/dataset.json
    - ID_6_SUBMISSION_nnUNetTrainerSkeletonRecall_NoMirroring__nnUNetResEncUNetMPlans__3d_fullres/plans.json
  size_mb: unknown

compatible_containers:
  - TopCoW-CLAIM:v2025.10.14

source:
  type: unknown
  origin: unknown
  url: unknown
  license: unknown

usage:
  command_example: |
    TBA
  input_format: unknown
  output_format: unknown

maintainers:
  - name: BioImaging Team
    email: imarcoss@cnic.es

tags:
  - circle-of-willis
  - neuroimaging
  - nnunet
  - yolo

performance:
  metrics: unknown
  gpu_memory_mb: unknown
  inference_time_ms: unknown

training:
  dataset: unknown
  framework_version: unknown

notes: TBA
