name: gpu-nvitk
channels:
  - morpheme
  - mosaic
  - nvidia
  - pytorch
  - conda-forge
  - mrtrix3
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=2.3.3
  # Conda-only / non-PyPI dependencies
  - freeimage>=3.18.0
  - mrtrix3>=3.0.8
  - libstdcxx-ng>=15.2.0
  - pip:
      # CUDA-enabled PyTorch wheels
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch==2.9.0+cu130
      - torchvision==0.24.0+cu130
      - cupy-cuda13x==13.6.0
      - cutensor-cu13>=2.3.0
      - nvidia-nccl-cu13>=2.27.0
      # Install the Python package from this repo
      - -e ../
      # - --no-build-isolation
      # - pyradiomics>=3.0.1a1
